theme: jekyll-theme-minimal
title: Behoblog
description: My personal software-engineering/dev(-op)/business blog
logo: assets/img/logo.png
google_analytics: UA-117997554-1
defaults:
  -
    values:
      author: "Mateusz Legięcki (Behoston)"
linkedin: https://www.linkedin.com/in/behoston/